name: CI

on:
  push:
  pull_request:

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
      
      - name: Sync the project
        run: uv sync --all-extras

      - name: Run tests
        run: uv run pytest
        
      - name: Run type checking
        run: uv run mypy

    